# build step
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ENV VITE_NODE_ENV=production
ENV NODE_ENV=production

RUN npm run build

# runtime step
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
