// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuInfo {
    #[prost(float, repeated, tag = "1")]
    pub cpu_usages: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RamInfo {
    #[prost(uint64, tag = "1")]
    pub total: u64,
    #[prost(uint64, tag = "2")]
    pub used: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestMessage {
    /// The number of pockets
    #[prost(enumeration = "InfoType", tag = "1")]
    pub info_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResponseMessage {
    #[prost(oneof = "response_message::Data", tags = "1, 2")]
    pub data: ::core::option::Option<response_message::Data>,
}
/// Nested message and enum types in `ResponseMessage`.
pub mod response_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        CpuInfo(super::CpuInfo),
        #[prost(message, tag = "2")]
        RamInfo(super::RamInfo),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InfoType {
    Cpu = 0,
    Ram = 1,
}
impl InfoType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Cpu => "CPU",
            Self::Ram => "RAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CPU" => Some(Self::Cpu),
            "RAM" => Some(Self::Ram),
            _ => None,
        }
    }
}
