# ---------- builder ----------
FROM rust:1.92 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs

RUN cargo build --release
RUN rm -rf src

COPY src ./src

RUN cargo build --release

# ---------- runtime ----------
FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/htop /app/server

EXPOSE 3000
CMD ["./server"]
