# ---------- builder ----------
FROM rust:1.92 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

COPY src ./src
RUN cargo build --release

# ---------- runtime ----------
FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/htop-api /app/server

ENV API_PORT=3000
EXPOSE 3000
CMD ["./server"]
