# ---- build stage ----
FROM rust:1.92 AS builder
WORKDIR /app

# 1️⃣ Copy dependency files first (for caching)
COPY Cargo.toml Cargo.lock ./

# 2️⃣ Copy source code
COPY src ./src

# 3️⃣ Build release binary
RUN cargo build --release

# ---- runtime stage ----
FROM debian:bookworm-slim
WORKDIR /app

# Copy the binary (rename if you want)
COPY --from=builder /app/target/release/htop /app/server

EXPOSE 3000

CMD ["./server"]
