/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.33.2
 * source: api.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace api {
    export enum InfoType {
        CPU = 0,
        RAM = 1
    }
    export class CpuInfo extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            cpu_usages?: number[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("cpu_usages" in data && data.cpu_usages != undefined) {
                    this.cpu_usages = data.cpu_usages;
                }
            }
        }
        get cpu_usages() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as number[];
        }
        set cpu_usages(value: number[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            cpu_usages?: number[];
        }): CpuInfo {
            const message = new CpuInfo({});
            if (data.cpu_usages != null) {
                message.cpu_usages = data.cpu_usages;
            }
            return message;
        }
        toObject() {
            const data: {
                cpu_usages?: number[];
            } = {};
            if (this.cpu_usages != null) {
                data.cpu_usages = this.cpu_usages;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.cpu_usages.length)
                writer.writePackedFloat(1, this.cpu_usages);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CpuInfo {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CpuInfo();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.cpu_usages = reader.readPackedFloat();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CpuInfo {
            return CpuInfo.deserialize(bytes);
        }
    }
    export class RamInfo extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            total?: number;
            used?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("total" in data && data.total != undefined) {
                    this.total = data.total;
                }
                if ("used" in data && data.used != undefined) {
                    this.used = data.used;
                }
            }
        }
        get total() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set total(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get used() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set used(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            total?: number;
            used?: number;
        }): RamInfo {
            const message = new RamInfo({});
            if (data.total != null) {
                message.total = data.total;
            }
            if (data.used != null) {
                message.used = data.used;
            }
            return message;
        }
        toObject() {
            const data: {
                total?: number;
                used?: number;
            } = {};
            if (this.total != null) {
                data.total = this.total;
            }
            if (this.used != null) {
                data.used = this.used;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.total != 0)
                writer.writeUint64(1, this.total);
            if (this.used != 0)
                writer.writeUint64(2, this.used);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RamInfo {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RamInfo();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.total = reader.readUint64();
                        break;
                    case 2:
                        message.used = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RamInfo {
            return RamInfo.deserialize(bytes);
        }
    }
    export class RequestMessage extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            info_type?: InfoType;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("info_type" in data && data.info_type != undefined) {
                    this.info_type = data.info_type;
                }
            }
        }
        get info_type() {
            return pb_1.Message.getFieldWithDefault(this, 1, InfoType.CPU) as InfoType;
        }
        set info_type(value: InfoType) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            info_type?: InfoType;
        }): RequestMessage {
            const message = new RequestMessage({});
            if (data.info_type != null) {
                message.info_type = data.info_type;
            }
            return message;
        }
        toObject() {
            const data: {
                info_type?: InfoType;
            } = {};
            if (this.info_type != null) {
                data.info_type = this.info_type;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.info_type != InfoType.CPU)
                writer.writeEnum(1, this.info_type);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RequestMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RequestMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.info_type = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RequestMessage {
            return RequestMessage.deserialize(bytes);
        }
    }
    export class ResponseMessage extends pb_1.Message {
        #one_of_decls: number[][] = [[1, 2]];
        constructor(data?: any[] | ({} & (({
            cpu_info?: CpuInfo;
            ram_info?: never;
        } | {
            cpu_info?: never;
            ram_info?: RamInfo;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("cpu_info" in data && data.cpu_info != undefined) {
                    this.cpu_info = data.cpu_info;
                }
                if ("ram_info" in data && data.ram_info != undefined) {
                    this.ram_info = data.ram_info;
                }
            }
        }
        get cpu_info() {
            return pb_1.Message.getWrapperField(this, CpuInfo, 1) as CpuInfo;
        }
        set cpu_info(value: CpuInfo) {
            pb_1.Message.setOneofWrapperField(this, 1, this.#one_of_decls[0], value);
        }
        get has_cpu_info() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get ram_info() {
            return pb_1.Message.getWrapperField(this, RamInfo, 2) as RamInfo;
        }
        set ram_info(value: RamInfo) {
            pb_1.Message.setOneofWrapperField(this, 2, this.#one_of_decls[0], value);
        }
        get has_ram_info() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get data() {
            const cases: {
                [index: number]: "none" | "cpu_info" | "ram_info";
            } = {
                0: "none",
                1: "cpu_info",
                2: "ram_info"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1, 2])];
        }
        static fromObject(data: {
            cpu_info?: ReturnType<typeof CpuInfo.prototype.toObject>;
            ram_info?: ReturnType<typeof RamInfo.prototype.toObject>;
        }): ResponseMessage {
            const message = new ResponseMessage({});
            if (data.cpu_info != null) {
                message.cpu_info = CpuInfo.fromObject(data.cpu_info);
            }
            if (data.ram_info != null) {
                message.ram_info = RamInfo.fromObject(data.ram_info);
            }
            return message;
        }
        toObject() {
            const data: {
                cpu_info?: ReturnType<typeof CpuInfo.prototype.toObject>;
                ram_info?: ReturnType<typeof RamInfo.prototype.toObject>;
            } = {};
            if (this.cpu_info != null) {
                data.cpu_info = this.cpu_info.toObject();
            }
            if (this.ram_info != null) {
                data.ram_info = this.ram_info.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_cpu_info)
                writer.writeMessage(1, this.cpu_info, () => this.cpu_info.serialize(writer));
            if (this.has_ram_info)
                writer.writeMessage(2, this.ram_info, () => this.ram_info.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ResponseMessage {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ResponseMessage();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.cpu_info, () => message.cpu_info = CpuInfo.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.ram_info, () => message.ram_info = RamInfo.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ResponseMessage {
            return ResponseMessage.deserialize(bytes);
        }
    }
}
